name: titer-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - jupyter
  - pandas
  - scikit-learn
  - python=3.11
  - scipy
  - numpy
  - seaborn
  - matplotlib
  - pip:
      - uv