[project]
name = "datahow-titer-ml"
version = "0.1.0"
description = "Predicting titer values for bioprocessing experiments using machine learning."
readme = "README.md"
authors = [
    { name = "Rangsiman Ketkaew", email = "rangsiman1993@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.0.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "scipy>=1.10.0",
    "scikit-learn>=1.3.0",
    "ruff>=0.16.2",
    "xgboost>=3.2.0",
    "fastapi[standard]>=0.141.1",
    "uvicorn>=0.52.3",
    "joblib>=1.5.3",
    "pyyaml>=6.0",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
]

[project.scripts]
datahow-titer-ml = "datahow_titer_ml:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
# Same as Black
line-length = 88

[tool.ruff.lint]
extend-select = ["E501"]

[tool.ruff.format]
quote-style = "double"
line-ending = "auto"
